apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    jsonData:
      version: Flux
      organization: puregold
      defaultBucket: ohlcv
      tlsSkipVerify: true
